services:
  db:
    image: postgres:latest
#    labels:
#      org.springframework.boot.ignore: true
    environment:
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: dummy_password
      POSTGRES_DB: book_catalog
    ports:
      - "5432:5432"