spring.application.name: book-catalog
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: main

---
spring:
  config:
    activate:
      on-profile: dev
  docker:
    compose:
      enabled: true
      file: compose.yaml
      lifecycle-management: start_and_stop
  jooq:
    sql-dialect: postgres
---

spring:
  jooq:
    sql-dialect: h2
  config:
    activate:
      on-profile: standalone
  docker:
    compose:
      enabled: false
  liquibase:
    contexts: main,test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:book-catalog;MODE=PostgreSQL
    username: sa
    password: password
  h2:
    console:
      enabled: true

logging.level:
  org.jooq: DEBUG
---
